#pragma once
#include <string>

using namespace std;

/**
 * @enum EUserStatus
 * @brief Defines the current status of a user account in the system.
 *
 * Active   - The user account is active and the user can log in.
 * Inactive - The user account is inactive and login is not allowed.
 * Blocked  - The user account is blocked due to failed login attempts
 *            or administrative action.
 * Error    - The user account status is invalid or could not be determined.
 */

enum class EUserStatus {
	Active,
	Inactive,
	Blocked,
	Error
};

/**
 * @class SUser
 * @brief Represents a user account used to log in to the system.
 *
 * _userName           - User account name. Lowercase letters only.
 * _role               - User role in the system (admin, employee, reader, etc.).
 * _userId             - Unique user identification number generated by the system.
 * _userStatus         - Current status of the user account.
 * _remainLoginAttempts - Number of remaining login attempts before the account
 *                        is automatically blocked.
 *
 * A newly created or successfully authenticated user has 5 login attempts.
 * Each failed login attempt decreases the number of remaining attempts by one.
 * When the number of remaining attempts reaches 0, the user account status
 * is changed to EUserStatus::Blocked.
 */

class SUser {
private:
	string _userName;
	char _role;
	string _userId;
	EUserStatus _userStatus;
	int _remainLoginAttempts;

public:
	SUser(const string &userName, 
		char role, 
		const string &userId, 
		EUserStatus userStatus, 
		int remainLoginAttempts) {
			_userName = userName;
			_role = role;
			_userId = userId;
			_userStatus = userStatus;
			_remainLoginAttempts = remainLoginAttempts;
	}

	string getUserName() {
		return this->_userName;
	}

	char getRole() {
		return this->_role;
	}

	string getUserId() {
		return this->_userId;
	}
	
	EUserStatus getUserStatus() {
		return this->_userStatus;
	}

	int getRemainLoginAttempts() {
		return this->_remainLoginAttempts;
	}

	void failedLoginAttempt() {
		if (_remainLoginAttempts > 0) _remainLoginAttempts--;
		if (_remainLoginAttempts == 0) _userStatus = EUserStatus::Blocked;
	}
};


/**
* @class SUserDetails
* @brief Stores additional information about a user.
*
* The information is stored in a file and may be stored in a database
* in the future.User details are linked to a user by the user ID.
*
* _firstName - User's first name.
* _lastName - User's last name.
* _phoneNumber - User's phone number.
* _userId - Unique user identification number.
* It must correspond to exactly one registered user.
*/

class SUserDetails {
private:
	string _firstName;
	string _lastName;
	string _phoneNumber;
	string _userId;

public:
	SUserDetails(string firstName, string lastName, string phoneNumber, string userId) {
		_firstName = firstName;
		_lastName = lastName;
		_phoneNumber = phoneNumber;
		_userId = userId;
	}

	string getFirstName() {
		return this->_firstName;

	}
	string getLastName() {
		return this->_lastName;

	}
	string getPhoneNumber() {
		return this->_phoneNumber;

	}
	string getUserId() {
		return this->_userId;
	}
};